### ISSUE TITLE
pgChess with Postgres 9.3dev

### ISSUE THREAD

**Issue by schmiddy** [gciolli/pgChess#2]
Hi,

I think pgChess needs some fixes to work with 9.3dev. When I try to compile git master, I get an error like:

src/chess.c:1046: warning: implicit declaration of function ‘heap_form_tuple’
src/chess.c:1046: warning: assignment makes pointer from integer without a cast

which is probably because of the recent htup header reorganization. A fix like this is enough to get src/chess.c to compile:

```
diff --git a/src/chess.c b/src/chess.c
index eb34f0c..4494e90 100644
--- a/src/chess.c
+++ b/src/chess.c
@@ -8,6 +8,11 @@
 PG_MODULE_MAGIC;
 #endif

+/* htup.h was reorganized for 9.3, so now we need this header */
+#if PG_VERSION_NUM >= 90300
+#include "access/htup_details.h"
+#endif
+
 /*
  * Memory context for formal_moves
  */
```

But then I see this error while running PG_v_PG.sql:

psql:var-play-2.sql:12: ERROR:  tuple to be updated was already modified by an operation triggered by the current command
HINT:  Consider using an AFTER trigger instead of a BEFORE trigger to propagate changes to other rows.
CONTEXT:  SQL statement "UPDATE status
    SET give_up = NOT apply_best_choice(depth_target)"
PL/pgSQL function ui_cpu_moves(interval,integer) line 21 at SQL statement
